//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversalApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_Products
    {
        public int id { get; set; }
        public Nullable<int> Product_id { get; set; }
        public string ProductName { get; set; }
        public Nullable<double> Price { get; set; }
    }
}
